(()=>{
  const products=[
    {id:'wedding-invitation',name:'Cinematic Wedding Invitation',category:'Events',price:null,mark:'20·12',badge:'New',theme:'wedding',preview:null,desc:'An editorial wedding invitation with a cinematic scroll entrance, refined event details and a luxurious mobile experience.',features:['3D scroll intro','Event details','Mobile first'],rank:1},
    {id:'bambis-bakery',name:"Bambi's Bakery",category:'Hospitality',price:null,mark:'BB',badge:'New',theme:'bakery',preview:null,desc:'A playful premium bakery concept built around a scroll-reactive cake reveal, warm storytelling and an irresistible visual rhythm.',features:['Scroll interaction','Story-led design','Responsive'],rank:2},
    {id:'velora-beauty',name:'Velora Beauty Link-in-Bio',category:'Link in bio',price:null,mark:'VB',badge:'Netlify',theme:'beauty',preview:null,type:'Netlify project',desc:'A polished beauty link hub that turns a social profile into a focused, high-end brand destination.',features:['Social links','Beauty editorial','Mobile first'],rank:3},
    {id:'limestone-cafe',name:'Limestone Café',category:'Hospitality',price:null,mark:'LC',badge:'Netlify live',theme:'limestone',preview:'https://jovial-empanada-edf643.netlify.app',type:'Live Netlify project',desc:'A warm neighbourhood café experience shaped around seasonal plates, beautiful coffee and a welcoming local story.',features:['Seasonal menu','Venue story','Responsive'],rank:4},
    {id:'brightforge-electrical',name:'Brightforge Electrical',category:'Trades',price:null,mark:'BF',badge:'Netlify live',theme:'brightforge',preview:'https://bright-forge.netlify.app',type:'Live Netlify project',desc:'A premium Sydney electrical website with clear services, confident workmanship and an effortless enquiry journey.',features:['Service paths','Local SEO','Lead capture'],rank:5},
    {id:'vanguard-relocations',name:'Vanguard Relocations',category:'Logistics',price:null,mark:'VR',badge:'Netlify live',theme:'vanguard',preview:'https://vanguardrelocations.netlify.app',type:'Live Netlify project',desc:'A trust-led relocation platform for home moves, business relocations, deliveries and specialist transport.',features:['Service discovery','Quote journey','Trust signals'],rank:6},
    {id:'vanguard-link-in-bio',name:'Vanguard Relocations Link-in-Bio',category:'Link in bio',price:null,mark:'VR',badge:'Netlify live',theme:'vanguard-bio',preview:'https://vanguardrelocations.netlify.app/links',type:'Live Netlify project',desc:'A focused mobile link hub that directs social visitors into online quotes, service discovery and secure booking payments.',features:['Online enquiries','Mobile first','Booking links'],rank:7},
    {id:'anand-motors',name:'Anand Motors',category:'Automotive',price:null,mark:'AM',badge:'Netlify live',theme:'anand',preview:'https://curious-medovik-eba893.netlify.app',type:'Live Netlify project',desc:'A premium automotive growth concept for a local service centre, built around standards, expertise and booking intent.',features:['Growth concept','Service booking','Local business'],rank:8},
    {id:'cafe-cicheti',name:'Cafe Cicheti & Co',category:'Hospitality',price:null,mark:'CC',badge:'Netlify live',theme:'cicheti',preview:'https://celebrated-begonia-5b191b.netlify.app',type:'Live Netlify project',desc:'A soulful café concept that pairs fresh food, warm hospitality and a contemporary neighbourhood identity.',features:['Menu showcase','Brand story','Mobile first'],rank:9},
    {id:'shineworks-detailing',name:'ShineWorks Detailing',category:'Automotive',price:null,mark:'SW',badge:'Netlify live',theme:'shineworks',preview:'https://willowy-starship-fa0ae6.netlify.app',type:'Live Netlify project',desc:'A polished mobile detailing website for car washing, interior care and ceramic coating at the customer’s door.',features:['Mobile service','Booking CTA','Service packages'],rank:10},
    {id:'shv-clean-service',name:'SHV Clean Service',category:'Home services',price:null,mark:'SHV',badge:'Netlify live',theme:'shv',preview:'https://marvelous-buttercream-cdcfb7.netlify.app',type:'Live Netlify project',desc:'A clear, reassuring Sydney cleaning website designed to turn residential and commercial visitors into quote requests.',features:['Quote capture','Service areas','Residential & commercial'],rank:11},
    {id:'link-hub',name:'BLVCK OAK Link Hub',category:'Link in bio',price:500,mark:'BO',badge:'Featured',preview:'https://blvck-oak-links.samkapa3.chatgpt.site',desc:'A high-motion social link hub with a premium personal-brand feel.',features:['3D motion','Social links','Mobile first'],rank:12},
    {id:'lumera',name:'LUMÉRA Beauty',category:'Ecommerce',price:1500,mark:'L°',badge:'Featured',preview:'previews/ecommerce.html',desc:'Luxury ecommerce direction designed around products, editorial storytelling and conversion.',features:['Product store','Collections','Premium motion'],rank:13},
    {id:'voltforge',name:'VoltForge Electrical',category:'Trades',price:1500,mark:'VF',preview:'previews/electrician.html',desc:'Trust-first electrician site with clear services, rapid enquiry paths and strong local positioning.',features:['Lead capture','Services','Local SEO'],rank:14},
    {id:'lumina',name:'Lumina Health',category:'Medical',price:1500,mark:'L+',preview:'previews/medical-booking.html',desc:'Calm healthcare booking concept with service discovery and appointment-focused customer flow.',features:['Appointments','Services','Trust UI'],rank:15},
    {id:'prismwash',name:'PrismWash Auto Spa',category:'Automotive',price:500,mark:'PW',preview:'previews/car-wash.html',desc:'Bold car-care landing experience for packages, bookings and visual service presentation.',features:['Packages','Booking CTA','Animation'],rank:16},
    {id:'embergrain',name:'Ember & Grain',category:'Hospitality',price:500,mark:'E&G',preview:'previews/cafe.html',desc:'Warm café concept for menu discovery, location details and brand-led storytelling.',features:['Menu','Location','Hospitality'],rank:17},
    {id:'aurelia',name:'Aurelia Dining Room',category:'Hospitality',price:1500,mark:'A.',preview:'previews/restaurant.html',desc:'Refined restaurant website direction for menus, reservations and an elevated dining brand.',features:['Reservations','Menus','Editorial'],rank:18},
    {id:'apex',name:'Apex Motorworks',category:'Automotive',price:1500,mark:'AM',preview:'previews/car-service.html',desc:'Performance-led mechanic and service-centre concept built around services and booking intent.',features:['Service list','Bookings','Trust'],rank:19},
    {id:'purehaus',name:'PureHaus Cleaning',category:'Home services',price:500,mark:'PH',preview:'previews/cleaning-service.html',desc:'Clean, direct service-business landing page with packages, proof and quote generation.',features:['Quotes','Packages','Reviews'],rank:20},
    {id:'verdant',name:'Verdant Form',category:'Landscaping',price:1500,mark:'VF',preview:'previews/landscaping.html',desc:'Visual landscaping experience made to showcase transformations, services and project enquiries.',features:['Projects','Services','Gallery'],rank:21},
    {id:'tablepulse',name:'TablePulse',category:'Hospitality',price:2900,mark:'TP',preview:'previews/qr-menu-ordering.html',desc:'QR menu and ordering concept for venues that want a faster digital ordering experience.',features:['QR ordering','Digital menu','Commerce'],rank:22}
  ];
  const directory=products.map((p,i)=>({...p,id:'biz-'+p.id,price:0,badge:i<2?'Demo listing':'Demo business',desc:`Demo directory listing showing how a ${p.category.toLowerCase()} business can present its services or products.`,features:[p.category,'Website','Services'],rank:p.rank}));
  const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const grid=$('[data-product-grid]'),chips=$('[data-chips]'),search=$('#market-search'),sort=$('#market-sort'),count=$('[data-result-count]'),modeLabel=$('[data-mode-label]'),dirIntro=$('[data-directory-intro]');
  let mode='websites',category='All';
  let favourites=new Set(JSON.parse(localStorage.getItem('bo-market-favs')||'[]'));
  let cart=JSON.parse(localStorage.getItem('bo-market-cart')||'[]').filter(id=>products.some(p=>p.id===id));
  const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);
  const hasPrice=p=>Number.isFinite(p.price);
  const displayPrice=p=>hasPrice(p)?money(p.price):'Custom quote';
  const activeData=()=>mode==='websites'?products:directory;
  function categories(){return ['All',...new Set(activeData().map(p=>p.category))]}
  function renderChips(){chips.innerHTML=categories().map(c=>`<button class="chip ${c===category?'active':''}" type="button" data-category="${c}">${c}</button>`).join('');$$('[data-category]',chips).forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;renderChips();render()}))}
  function filtered(){const q=search.value.trim().toLowerCase();let arr=activeData().filter(p=>(category==='All'||p.category===category)&&(!q||[p.name,p.category,p.desc,...p.features].join(' ').toLowerCase().includes(q)));const priceOrder=(a,b,direction)=>hasPrice(a)!==hasPrice(b)?(hasPrice(a)?-1:1):hasPrice(a)?direction*(a.price-b.price)||a.rank-b.rank:a.rank-b.rank;switch(sort.value){case'price-low':arr.sort((a,b)=>priceOrder(a,b,1));break;case'price-high':arr.sort((a,b)=>priceOrder(a,b,-1));break;case'name':arr.sort((a,b)=>a.name.localeCompare(b.name));break;default:arr.sort((a,b)=>a.rank-b.rank)}return arr}
  function card(p){const isFav=favourites.has(p.id);const inCart=cart.includes(p.id);const business=mode==='businesses';const preview=p.preview?`<a href="${p.preview}" target="_blank" rel="noopener noreferrer">${business?'Visit demo':'Live preview'} ↗</a>`:`<a href="contact.html?service=concept-preview&amp;concept=${encodeURIComponent(p.name)}">Preview by request ↗</a>`;const visual=p.preview?`<a class="site-preview-link" href="${p.preview}" target="_blank" rel="noopener noreferrer" aria-label="Open ${p.name} website preview"><span class="site-preview-browser"><span class="site-preview-bar"><i></i><i></i><i></i><b>${p.name}</b></span><iframe src="${p.preview}" title="${p.name} website preview" loading="lazy" tabindex="-1" aria-hidden="true"></iframe></span><span class="site-preview-open">Click to open website ↗</span></a>`:`<a class="site-preview-link site-preview-request" href="contact.html?service=concept-preview&amp;concept=${encodeURIComponent(p.name)}" aria-label="Request a preview of ${p.name}"><span class="product-monogram">${p.mark}</span><span class="site-preview-open">Request website preview ↗</span></a>`;return `<article class="product-card"><div class="product-visual theme-${p.theme||'oak'}"><span class="product-badge ${business?'verified':''}">${business?'DEMO DIRECTORY':(p.badge||p.category)}</span><button class="fav ${isFav?'active':''}" type="button" data-fav="${p.id}" aria-label="${isFav?'Remove from':'Add to'} favourites">${isFav?'♥':'♡'}</button>${visual}</div><div class="product-body"><div class="product-meta"><span>${p.category}</span><span>${business?'Directory preview':(p.type||'Black Oak concept')}</span></div><h3>${p.name}</h3><p class="product-desc">${p.desc}</p><div class="feature-list">${p.features.map(f=>`<span>${f}</span>`).join('')}</div><div class="price-line"><div><small>${business?'Listing type':hasPrice(p)?'Build starts from':'Tailored scope'}</small><div class="price">${business?'Business profile':displayPrice(p)}</div></div><small>${business?'Demo only':hasPrice(p)?'AUD':'Enquire'}</small></div><div class="card-actions">${preview}${business?`<a class="primary" href="contact.html?service=business-directory">List business</a>`:`<button class="primary" type="button" data-cart-add="${p.id}">${inCart?'Shortlisted ✓':'Add to shortlist'}</button>`}</div></div></article>`}
  function render(){const arr=filtered();count.textContent=arr.length;grid.innerHTML=arr.length?arr.map(card).join(''):`<div class="empty"><strong>No matches yet.</strong>Try another search or category.</div>`;$$('[data-fav]',grid).forEach(b=>b.addEventListener('click',()=>toggleFav(b.dataset.fav)));$$('[data-cart-add]',grid).forEach(b=>b.addEventListener('click',()=>addCart(b.dataset.cartAdd)))}
  function toggleFav(id){favourites.has(id)?favourites.delete(id):favourites.add(id);localStorage.setItem('bo-market-favs',JSON.stringify([...favourites]));render()}
  function addCart(id){if(!cart.includes(id))cart.push(id);saveCart();render();openCart()}
  function removeCart(id){cart=cart.filter(x=>x!==id);saveCart();render();renderCart()}
  function saveCart(){localStorage.setItem('bo-market-cart',JSON.stringify(cart));$('[data-cart-count]').textContent=cart.length;renderCart()}
  function renderCart(){const host=$('[data-cart-items]');const selected=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);host.innerHTML=selected.length?selected.map(p=>`<div class="cart-item"><div class="cart-item-mark">${p.mark}</div><div><strong>${p.name}</strong><small>${p.category} · ${hasPrice(p)?`from ${money(p.price)}`:'custom quote'}</small></div><button class="remove-item" type="button" data-remove="${p.id}" aria-label="Remove ${p.name}">×</button></div>`).join(''):`<div class="cart-empty">Your shortlist is empty.<br>Add website styles while you browse.</div>`;const pricedTotal=selected.filter(hasPrice).reduce((sum,p)=>sum+p.price,0);const hasCustom=selected.some(p=>!hasPrice(p));$('[data-cart-total]').textContent=hasCustom?(pricedTotal?`${money(pricedTotal)} + quote`:'Custom quote'):money(pricedTotal);const link=$('[data-send-shortlist]');link.href=selected.length?`quote.html?marketplace=${encodeURIComponent(selected.map(p=>p.name).join(', '))}`:'quote.html';$$('[data-remove]',host).forEach(b=>b.addEventListener('click',()=>removeCart(b.dataset.remove)))}
  const drawer=$('[data-cart-drawer]'),backdrop=$('[data-drawer-backdrop]');function openCart(){drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false')}function closeCart(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
  $('[data-open-cart]').addEventListener('click',openCart);$('[data-close-cart]').addEventListener('click',closeCart);backdrop.addEventListener('click',closeCart);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});
  function setMode(next){mode=next;category='All';$$('[data-mode]').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});dirIntro.classList.toggle('active',mode==='businesses');modeLabel.textContent=mode==='websites'?'Website designs ready to shortlist':'Demo directory listings — real client opt-in ready';search.placeholder=mode==='websites'?'Search websites, industries or features…':'Search businesses, services or products…';renderChips();render()}
  $$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('[data-open-directory]').addEventListener('click',()=>{setMode('businesses');document.querySelector('#shop').scrollIntoView({behavior:'smooth'})});search.value=new URLSearchParams(location.search).get('search')||'';search.addEventListener('input',render);sort.addEventListener('change',render);
  renderChips();render();saveCart();
})();
