// Curated fictional AI concepts. These records are never authentication users.
const groups = [
['Home & living', [
['Forma Habitat','Sculptural living, thoughtfully made.','Modular sofa|Travertine side table|Linen lounge chair'],
['Moss & Mortar','Bring the outside into everyday living.','Moss wall panel|Botanical planter|Terrarium kit'],
['Fold House','Big ideas for smaller spaces.','Folding desk|Wall storage system|Compact dining set'],
['Clay Ritual','Objects with a softer edge.','Hand-shaped bowl|Ceramic vase|Stoneware cup'],
['Luma Nest','Light that changes the room.','Arc floor lamp|Paper pendant|Bedside glow lamp'],
['Woven North','Texture you can come home to.','Wool throw|Woven cushion|Natural fibre rug'],
['Still Oak','Furniture for a slower life.','Oak bench|Reading chair|Solid timber shelf'],
['Pebble Studio','Small objects. Quiet presence.','Sculpture set|Desk organiser|Incense holder'],
['Atlas Rooms','A new perspective on your space.','Room styling concept|Colour consultation|Furniture layout'],
['Sunday Shelf','Make room for the things you love.','Floating shelf|Bookcase|Display cabinet']]],
['Fashion', [
['Noir Assembly','A wardrobe without the noise.','Structured jacket|Wide-leg trouser|Everyday tee'],
['Sol Thread','Dress for the golden hour.','Linen co-ord|Summer shirt|Wrap skirt'],
['Orbit Athletics','Built for your next move.','Training top|Running shorts|Stretch leggings'],
['Indigo Archive','Denim with a different story.','Straight denim|Workwear overshirt|Denim tote'],
['Pearl Avenue','Little details, lasting impressions.','Pearl earrings|Pendant necklace|Stacking ring'],
['Dune Footwear','Find your own ground.','Suede loafer|Everyday sneaker|Leather sandal'],
['Marrow Leather','Carry less. Carry better.','Crossbody bag|Card wallet|Travel pouch'],
['Velvet Hour','Make an entrance, your way.','Evening dress|Satin clutch|Statement scarf'],
['Patch Playground','Colour outside the lines.','Patchwork hoodie|Graphic cap|Colour-block socks'],
['Coastline Optical','See the brighter side.','Square sunglasses|Round frames|Lens case']]],
['Beauty', [
['Petal Theory','A little colour, a lot of you.','Lip tint|Cream blush|Brow palette'],
['Satin Skin','Your daily moment of calm.','Face cleanser concept|Moisturiser concept|Skin-care travel kit'],
['Muse Nails','Tiny canvases. Endless expression.','Press-on nail set|Nail art session|Cuticle care kit'],
['Amber Aura','Wear a memory.','Amber fragrance|Discovery scent set|Solid perfume'],
['Crown & Coil','Celebrate every curl.','Curl styling session|Satin bonnet|Wide-tooth comb'],
['Bloom Brush','Tools for your own kind of beauty.','Brush set|Makeup sponge|Travel brush case'],
['Halo Atelier','Beauty for your biggest moments.','Bridal makeup concept|Event makeup concept|Makeup lesson'],
['River Soap','Everyday rituals, refreshed.','Botanical soap|Soap dish|Bath gift box'],
['Bronze Muse','Glow in your own light.','Bronzer palette|Highlight balm|Body shimmer'],
['Rosewood Studio','An appointment with yourself.','Hair styling concept|Hair colour consultation|Blow-dry concept']]],
['Food & drink', [
['Flour Poetry','Something wonderful is rising.','Sourdough loaf|Morning pastry box|Celebration cake'],
['Morrow Coffee','A better beginning.','House coffee blend|Cold brew bottle|Coffee tasting kit'],
['Ember Table','Gather around something good.','Seasonal tasting menu|Private dining concept|Dinner gift experience'],
['Matcha Meadow','Take a greener pause.','Matcha tin|Bamboo whisk|Matcha bowl'],
['Cocoa Atlas','Follow your taste somewhere new.','Dark chocolate bar|Truffle collection|Chocolate tasting box'],
['Citrus Picnic','Pack a little sunshine.','Picnic grazing box|Fruit tart|Citrus cordial'],
['Pasta Post','A little Italy at your table.','Fresh pasta box|Tomato sauce|Pasta-making session'],
['Spice Caravan','Stories told in flavour.','Spice blend trio|Chilli crisp|Cooking workshop'],
['Honey Harbour','Good things take their time.','Honey jar|Honey gift set|Beeswax wrap'],
['Midnight Scoops','Save room for the unexpected.','Ice cream pint|Dessert flight|Party scoop cart']]],
['Creative services', [
['Pixel Orchard','Ideas, ready to grow.','Brand identity concept|Website art direction|Launch graphics'],
['Frame & Field','Ordinary moments, beautifully seen.','Portrait session concept|Product photography concept|Event coverage concept'],
['Ink Current','Words that move people.','Website copy package|Brand voice guide|Email campaign concept'],
['Motion Harbour','Give your story movement.','Logo animation concept|Explainer storyboard|Social motion pack'],
['Paper Satellite','For moments worth sending.','Wedding stationery concept|Invitation suite|Thank-you cards'],
['Sound Lantern','Find the sound of your story.','Podcast editing concept|Brand sound concept|Audio intro concept'],
['Grid Society','Clarity in every detail.','Editorial layout|Presentation design|Report design'],
['Colour Assembly','A fresh point of view.','Illustration commission concept|Packaging artwork|Mural design concept'],
['Studio Elsewhere','Make your next chapter visible.','Creative direction|Campaign concept|Visual moodboard'],
['Type Garden','Let the letters do the talking.','Lettering concept|Typography poster|Wordmark design']]],
['Local services', [
['Clear Tide','A fresher space starts here.','Home cleaning concept|End-of-lease cleaning concept|Window cleaning concept'],
['Greenline Gardens','Give your outdoors room to grow.','Garden design concept|Planting plan|Courtyard makeover concept'],
['Spark Avenue','Bright ideas for everyday spaces.','Lighting design concept|Home electrical enquiry|Switchboard enquiry'],
['Flow District','Keep your day flowing.','Plumbing enquiry|Tap replacement enquiry|Bathroom plumbing concept'],
['Torque House','Keep your journey moving.','Vehicle service enquiry|Inspection enquiry|Detailing concept'],
['Lift & Lane','A fresh start, carefully handled.','Home move concept|Packing service concept|Office move concept'],
['Brush Borough','A change of colour changes everything.','Interior painting concept|Exterior painting concept|Colour matching concept'],
['Paw Parade','More joy for your best friend.','Dog walking concept|Pet grooming concept|Pet sitting concept'],
['Fix Foundry','Small fixes. A better home.','Furniture assembly concept|Shelf installation concept|Home maintenance concept'],
['Pool & Palm','Bring the holiday home.','Pool care concept|Outdoor styling concept|Patio refresh concept']]],
['Technology', [
['Loop Desk','Make space for focused work.','Desk planner concept|Focus timer concept|Workflow dashboard concept'],
['Signal Forge','Turn complex data into clarity.','Analytics dashboard design|Reporting template|Data visualisation concept'],
['Cloud Sprout','An organised start for small teams.','Team workspace concept|Project tracker concept|Client portal design'],
['Prompt Loom','Weave better ideas together.','Prompt library concept|AI workflow blueprint|Writing assistant concept'],
['Circuit Cove','Everyday tech, considered.','Keyboard concept|Desk charging dock|Cable management kit'],
['Nimble Cart','A smoother path from browse to basket.','Storefront design|Product page concept|Checkout UX review'],
['Quiet Stack','Simple tools for busy minds.','Notes app concept|Daily planner concept|Reading list concept'],
['Vector Bloom','Give your product a visual voice.','Icon collection|UI component kit|Design token set'],
['Metric Moon','Make the numbers make sense.','Business dashboard concept|Goal tracker concept|Weekly report template'],
['Launch Relay','From idea to first impression.','Landing page concept|Product launch checklist|Waitlist page design']]],
['Fitness & outdoors', [
['Trail Chapter','Your next story starts outside.','Day pack|Trail bottle|Hiking route journal'],
['Rise Movement','Move at your own pace.','Movement class concept|Training journal|Exercise mat'],
['Tide Surf','Follow the swell.','Surfboard concept|Board bag|Surf lesson enquiry'],
['Summit Supply','Go a little further.','Camp lantern|Camping mug|Travel hammock'],
['Pedal District','Take the scenic route.','City bicycle concept|Cycling bag|Ride journal'],
['Flow Mat','A little room to breathe.','Yoga mat|Cork block|Stretch class concept'],
['Court Culture','Find your game.','Racket bag|Court tee|Practice session concept'],
['Roam Running','One more street. One more sunrise.','Running cap|Hydration belt|Run planner'],
['Basecamp Kitchen','Eat well, anywhere.','Camp cook set|Travel cutlery|Coffee brewer'],
['Ocean Interval','Made for days by the water.','Swim bag|Quick-dry towel|Waterproof pouch']]],
['Events & experiences', [
['Golden Gather','Make the moment feel like you.','Event styling concept|Table setting concept|Celebration moodboard'],
['Wildflower Vows','Your story, beautifully celebrated.','Wedding styling concept|Floral installation concept|Ceremony design'],
['Wonder Workshop','Try something for the first time.','Pottery workshop concept|Painting workshop concept|Craft party concept'],
['Neon Social','Good company. Great nights.','Party styling concept|Photo booth concept|DJ event concept'],
['Little Lanterns','Big wonder for little people.','Kids party concept|Craft activity kit|Birthday styling concept'],
['Atlas Weekends','Find your next little escape.','Weekend itinerary concept|City guide|Travel planning session'],
['Table Stories','Bring your people together.','Dinner party styling|Tablescape kit|Host planning guide'],
['Bloom Parcel','Say it with something thoughtful.','Flower arrangement concept|Gift hamper concept|Personalised note set'],
['Open Air Cinema','A screen under the stars.','Garden cinema concept|Outdoor party concept|Movie-night styling'],
['Chapter Retreats','A different kind of pause.','Creative retreat concept|Team day concept|Reflection journal']]],
['Art & digital goods', [
['Horizon Prints','A new view, every day.','Landscape art print|Abstract poster|Gallery wall set'],
['Monday Paper','Plan a little possibility.','Digital planner|Habit journal|Weekly desk pad'],
['Obsidian Pixels','Worlds beyond the ordinary.','Game art pack|Pixel character set|Fantasy wallpaper'],
['Soft Geometry','Shape your surroundings.','Geometric print|Pattern collection|Desktop wallpaper'],
['Analog Letters','The joy of putting pen to paper.','Notebook|Letter-writing set|Daily reflection cards'],
['Dream Render','Imagine another dimension.','3D scene concept|Product render concept|Digital sculpture'],
['Muse Market','Make your next idea easier.','Presentation template|Social design kit|Portfolio layout'],
['Tiny Universe','Small art. Big imagination.','Miniature sculpture concept|Art postcard set|Collector print'],
['Wild Type','Words with a wilder side.','Display lettering pack|Quote print|Custom monogram concept'],
['Afterglow Editions','Keep a little of the light.','Photography print|Seasonal art collection|Digital photo zine']]]
];
const palettes = [
['#e9e4d8','#272c24','#536244'],['#15171d','#f2efe7','#c1a8fa'],['#f8e7dd','#4b2927','#a64032'],['#e4eee9','#143830','#347c62'],['#f0ecff','#32264c','#7552ae'],['#151515','#f9eacc','#b29458'],['#e6eff8','#182c47','#336ead'],['#f5edb7','#3b371c','#76631e'],['#fae4ed','#571d38','#a13762'],['#e9e9e5','#25252a','#686878']
];
const styles = ['Editorial','Midnight luxe','Playful studio','Botanical','Soft gradient','Gallery','Technical','Retro','Expressive','Minimal'];
export const profiles = groups.flatMap(([category,rows],g)=> rows.map(([name,tagline,items],j)=>{
 const i=g*10+j, theme=(j+g*3)%10;
 return {id:`ai-${String(i+1).padStart(3,'0')}`,slug:name.toLowerCase().replace(/ & /g,'-and-').replace(/[^a-z0-9]+/g,'-'),name,category,tagline,offerings:items.split('|'),style:styles[theme],theme,layout:(j+g)%5,palette:palettes[theme],aiGenerated:true,fictional:true,transactionsEnabled:false,bio:`${name} is an AI-created ${category.toLowerCase()} concept exploring ${styles[theme].toLowerCase()} design. Discover its visual identity, website direction and sample offerings.`,number:i+1};
}));
